name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      # If the Gradle wrapper is missing, create it (no local Gradle needed).
      - name: Ensure Gradle wrapper exists
        shell: bash
        run: |
          if [ ! -f android/gradlew ]; then
            sudo apt-get update -y
            sudo apt-get install -y gradle
            cd android
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x android/gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DispatchOne-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
